language: java
jdk: 
  - openjdk8
  - openjdk11
services: mysql
script:
  - mvn test -DargLine="-Dcontiperf.active=false"
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notifications:
  email:
    recipients:
      - aitorpiris@opendeusto.es
      - iratxe.campo@opendeusto.es
      - eneko.perez@opendeusto.es
    on_success: never
    on_failure: always
