language: java
notifications: 
  email: 
    on_failure: always
    on_success: never
    recipients: 
      - aitorpiris@opendeusto.es
      - iratxe.campo@opendeusto.es
      - eneko.perez@opendeusto.es
